#!/usr/bin/env bash
set -euo pipefail

# 5xH200 full-vocab OPD test:
#   GPU0-1: OLMo3Sink trainer
#   GPU2:   OLMo3Sink policy rollout
#   GPU3-4: DeepSeek-V4-Flash teacher hidden-state scorer (TP=2)
#
# This keeps the main 4x command as the single implementation surface and only
# overrides the run shape and full-vocab distillation knobs.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export OLMO_RUN_DIR_NAME="${OLMO_RUN_DIR_NAME:-prime_rl_opd_full_vocab_dpsk_ctx24576_5h200_2train_1policy_2teacher_$(date -u +%Y%m%d_%H%M%S)}"

export PRIME_OPD_MODEL_PATH="${PRIME_OPD_MODEL_PATH:-/vol/olmo_train_assets/models/opd-32b-v33-s150/opd-32b-v33-s150}"
export PRIME_OPD_TEACHER_MODEL_PATH="${PRIME_OPD_TEACHER_MODEL_PATH:-/vol/olmo_train_assets/models/dpsk-v4-flash}"
export PRIME_OPD_FULL_VOCAB_TEACHER_LM_HEAD_PATH="${PRIME_OPD_FULL_VOCAB_TEACHER_LM_HEAD_PATH:-${PRIME_OPD_TEACHER_MODEL_PATH}}"
export PRIME_OPD_FULL_VOCAB_TEACHER_LM_HEAD_KEY="${PRIME_OPD_FULL_VOCAB_TEACHER_LM_HEAD_KEY:-head.weight}"
export PRIME_OPD_FULL_VOCAB_TEACHER_HIDDEN_DTYPE="${PRIME_OPD_FULL_VOCAB_TEACHER_HIDDEN_DTYPE:-bfloat16}"
export PRIME_OPD_FULL_VOCAB_TOKEN_CHUNK_SIZE="${PRIME_OPD_FULL_VOCAB_TOKEN_CHUNK_SIZE:-32}"
export PRIME_OPD_FULL_VOCAB_VOCAB_CHUNK_SIZE="${PRIME_OPD_FULL_VOCAB_VOCAB_CHUNK_SIZE:-8192}"
export PRIME_OPD_DISTILL_MODE="${PRIME_OPD_DISTILL_MODE:-full_vocab_hidden}"
export PRIME_OPTIMIZER="${PRIME_OPTIMIZER:-te_fused_adamw}"

export PRIME_TRAIN_GPUS="${PRIME_TRAIN_GPUS:-2}"
export PRIME_INFER_GPUS="${PRIME_INFER_GPUS:-1}"
export PRIME_GPUS_PER_NODE="${PRIME_GPUS_PER_NODE:-5}"
export PRIME_OPD_TEACHER_GPU_IDS="${PRIME_OPD_TEACHER_GPU_IDS:-3,4}"
export PRIME_OPD_TEACHER_TP="${PRIME_OPD_TEACHER_TP:-2}"
export PRIME_OPD_TEACHER_DP="${PRIME_OPD_TEACHER_DP:-1}"
export PRIME_TRAINER_CP="${PRIME_TRAINER_CP:-1}"

export PRIME_OPD_CTX_LEN="${PRIME_OPD_CTX_LEN:-24576}"
export PRIME_OPD_VLLM_MAX_MODEL_LEN="${PRIME_OPD_VLLM_MAX_MODEL_LEN:-49152}"
export PRIME_VLLM_MAX_MODEL_LEN="${PRIME_VLLM_MAX_MODEL_LEN:-49152}"
export PRIME_OPD_COMPLETION_TOKENS="${PRIME_OPD_COMPLETION_TOKENS:-24576}"
export PRIME_OPD_EVAL_COMPLETION_TOKENS="${PRIME_OPD_EVAL_COMPLETION_TOKENS:-40960}"
export MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-40}"

export PRIME_OPD_BATCHED_TOKENS="${PRIME_OPD_BATCHED_TOKENS:-16384}"
export PRIME_OPD_POLICY_MAX_NUM_SEQS="${PRIME_OPD_POLICY_MAX_NUM_SEQS:-16}"
export PRIME_OPD_TEACHER_MAX_NUM_SEQS="${PRIME_OPD_TEACHER_MAX_NUM_SEQS:-24}"
export PRIME_OPD_MAX_INFLIGHT_ROLLOUTS="${PRIME_OPD_MAX_INFLIGHT_ROLLOUTS:-16}"
export PRIME_BATCH_SIZE="${PRIME_BATCH_SIZE:-2}"
export PRIME_GROUP_SIZE="${PRIME_GROUP_SIZE:-2}"

export PRIME_OPD_TEACHER_GPU_MEMORY_UTILIZATION="${PRIME_OPD_TEACHER_GPU_MEMORY_UTILIZATION:-0.95}"
export PRIME_OPD_POLICY_GPU_MEMORY_UTILIZATION="${PRIME_OPD_POLICY_GPU_MEMORY_UTILIZATION:-0.90}"
export PRIME_OPD_TEACHER_VLLM_ENFORCE_EAGER="${PRIME_OPD_TEACHER_VLLM_ENFORCE_EAGER:-false}"
export PRIME_VLLM_ENFORCE_EAGER="${PRIME_VLLM_ENFORCE_EAGER:-false}"
export PRIME_OPD_TEACHER_USE_DEEP_GEMM="${PRIME_OPD_TEACHER_USE_DEEP_GEMM:-true}"
export PRIME_OPD_TEACHER_VLLM_EXTRA="${PRIME_OPD_TEACHER_VLLM_EXTRA:-{\"kv_cache_dtype\":\"fp8\",\"block_size\":256,\"enable_expert_parallel\":true,\"linear_backend\":\"deep_gemm\"}}"

export PRIME_PROOF_NUM_VERIFIERS="${PRIME_PROOF_NUM_VERIFIERS:-4}"
export PRIME_PROOF_REFINE_ROUNDS="${PRIME_PROOF_REFINE_ROUNDS:-0}"
export PRIME_PROOF_REFINE_REVIEW_N="${PRIME_PROOF_REFINE_REVIEW_N:-2}"

# Keep the cost of this full-vocab systems test bounded while still producing
# an end-of-run verifiable snapshot.
export PRIME_OPD_EVAL_INTERVAL="${PRIME_OPD_EVAL_INTERVAL:-40}"
export PRIME_OPD_EVAL_NUM_EXAMPLES="${PRIME_OPD_EVAL_NUM_EXAMPLES:-4}"
export PRIME_OPD_EVAL_GROUP_SIZE="${PRIME_OPD_EVAL_GROUP_SIZE:-1}"

export WANDB_MODE="${WANDB_MODE:-online}"
export WANDB_PROJECT="${WANDB_PROJECT:-olmo3-prime-rl-full-vocab}"

exec bash "${SCRIPT_DIR}/prime_rl_opd_4xh200_muon_imo_ctx16384_2train_1policy_1teacher.sh"
