#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_STAMP="${PRIME_SMOKE_RUN_STAMP:-$(date -u +%Y%m%dT%H%M%SZ)}"
RUN_NAME="${OLMO_RUN_DIR_NAME:-prime_opd_raw_g2_ctx8192_${RUN_STAMP}}"
RUN_ROOT="${PRIME_SMOKE_ROOT:-/alloc/prime-opd-smoke}/${RUN_NAME}"

mkdir -p "${RUN_ROOT}"
printf '%s\n' "${RUN_ROOT}" > "${PRIME_SMOKE_ROOT:-/alloc/prime-opd-smoke}/latest_run"

export CUDA_VERSION="${CUDA_VERSION:-12.8.1}"
export GLOBAL_RANK=0
export OLMO_RUN_DIR_NAME="${RUN_NAME}"
export PRIME_NODE_LAYOUT=1node
export PRIME_SINGLE_NODE_LABEL=0
export PRIME_TRAIN_PYTHON="${PRIME_TRAIN_PYTHON:-/usr/local/bin/python}"
export PRIME_TRAIN_ENTRYPOINT="${PRIME_TRAIN_ENTRYPOINT:-/opt/aimo-proof-pilot/src/train.py}"

export PRIME_OPD_MODEL_PATH="${PRIME_OPD_MODEL_PATH:-/alloc/models/opd-32b-deploy/opd-32b-deploy}"
export PRIME_OPD_TEACHER_MODEL_PATH="${PRIME_OPD_TEACHER_MODEL_PATH:-/alloc/models/dpsk-v4-flash}"
export PRIME_3NODE_TMP_ROOT="${PRIME_3NODE_TMP_ROOT:-${RUN_ROOT}}"
export PRIME_3NODE_RENDEZVOUS_DIR="${PRIME_3NODE_RENDEZVOUS_DIR:-${RUN_ROOT}/rdzv}"
export PRIME_3NODE_RUNTIME_BASE="${PRIME_3NODE_RUNTIME_BASE:-${RUN_ROOT}/runtime}"
export PRIME_OPD_OUTPUT_ROOT="${PRIME_OPD_OUTPUT_ROOT:-${RUN_ROOT}/output}"
export PRIME_OPD_LOG_ROOT="${PRIME_OPD_LOG_ROOT:-${RUN_ROOT}/logs}"
export PRIME_OPD_CHECKPOINT_ROOT="${PRIME_OPD_CHECKPOINT_ROOT:-${RUN_ROOT}/checkpoints}"

# The raw Prime node is CUDA 12.8 and already carries a compatible vLLM 0.24
# build. The main cluster command otherwise pins a CUDA 13 development wheel.
export PRIME_RL_RUNTIME_INSTALL_VLLM="${PRIME_RL_RUNTIME_INSTALL_VLLM:-0}"
export PRIME_RL_RUNTIME_VLLM_EXPECTED_VERSION="${PRIME_RL_RUNTIME_VLLM_EXPECTED_VERSION:-0.24.0}"

# One-node allocation: policy GPUs 0-1, trainer GPUs 2-3, teacher GPUs 6-7.
export PRIME_TRAIN_GPUS="${PRIME_TRAIN_GPUS:-2}"
export PRIME_VLLM_TP="${PRIME_VLLM_TP:-1}"
export PRIME_VLLM_DP="${PRIME_VLLM_DP:-2}"
export PRIME_VLLM_API_SERVER_COUNT="${PRIME_VLLM_API_SERVER_COUNT:-2}"
export PRIME_OPD_TEACHER_TP="${PRIME_OPD_TEACHER_TP:-2}"
export PRIME_OPD_TEACHER_DP="${PRIME_OPD_TEACHER_DP:-1}"
export PRIME_OPD_TEACHER_GPU_IDS="${PRIME_OPD_TEACHER_GPU_IDS:-6,7}"

export MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-2}"
export PRIME_OPD_CTX_LEN="${PRIME_OPD_CTX_LEN:-8192}"
export PRIME_OPD_VLLM_MAX_MODEL_LEN="${PRIME_OPD_VLLM_MAX_MODEL_LEN:-8192}"
export PRIME_OPD_COMPLETION_TOKENS="${PRIME_OPD_COMPLETION_TOKENS:-2048}"
export PRIME_OPD_EVAL_COMPLETION_TOKENS="${PRIME_OPD_EVAL_COMPLETION_TOKENS:-1024}"
export PRIME_OPD_BATCHED_TOKENS="${PRIME_OPD_BATCHED_TOKENS:-16384}"
export PRIME_OPD_TEACHER_BATCHED_TOKENS="${PRIME_OPD_TEACHER_BATCHED_TOKENS:-8192}"
export PRIME_OPD_POLICY_MAX_NUM_SEQS="${PRIME_OPD_POLICY_MAX_NUM_SEQS:-12}"
export PRIME_OPD_TEACHER_MAX_NUM_SEQS="${PRIME_OPD_TEACHER_MAX_NUM_SEQS:-1}"
export PRIME_OPD_MAX_INFLIGHT_ROLLOUTS="${PRIME_OPD_MAX_INFLIGHT_ROLLOUTS:-12}"

export PRIME_BATCH_SIZE="${PRIME_BATCH_SIZE:-2}"
export PRIME_GROUP_SIZE="${PRIME_GROUP_SIZE:-2}"
export PRIME_PROOF_CANDIDATE_CONTINUE_COUNT="${PRIME_PROOF_CANDIDATE_CONTINUE_COUNT:-1}"
export PRIME_PACKED_SEQUENCES_PER_STEP="${PRIME_PACKED_SEQUENCES_PER_STEP:-2}"
export PRIME_MAX_OFF_POLICY_STEPS="${PRIME_MAX_OFF_POLICY_STEPS:-2}"
export PRIME_PROOF_NUM_VERIFIERS="${PRIME_PROOF_NUM_VERIFIERS:-1}"
export PRIME_PROOF_REFINE_ROUNDS="${PRIME_PROOF_REFINE_ROUNDS:-0}"
export PRIME_PROOF_REFINE_REVIEW_N="${PRIME_PROOF_REFINE_REVIEW_N:-1}"

export PRIME_OPD_EVAL_INTERVAL="${PRIME_OPD_EVAL_INTERVAL:-100}"
export PRIME_OPD_EVAL_NUM_EXAMPLES="${PRIME_OPD_EVAL_NUM_EXAMPLES:-1}"
export PRIME_OPD_EVAL_GROUP_SIZE="${PRIME_OPD_EVAL_GROUP_SIZE:-1}"
export PRIME_CHECKPOINT_INTERVAL="${PRIME_CHECKPOINT_INTERVAL:-0}"
export PRIME_TRAINER_FP8="${PRIME_TRAINER_FP8:-true}"
export PRIME_TRAINER_COMPILE="${PRIME_TRAINER_COMPILE:-true}"
export PRIME_VLLM_ENFORCE_EAGER=false
export PRIME_OPD_TEACHER_VLLM_ENFORCE_EAGER=false
export WANDB_MODE=online
export WANDB_PROJECT="${WANDB_PROJECT:-olmo3-prime-rl-full-vocab}"

echo "[prime-opd-smoke] run_root=${RUN_ROOT} policy_dp=${PRIME_VLLM_DP} inflight=${PRIME_OPD_MAX_INFLIGHT_ROLLOUTS}"
exec bash "${SCRIPT_DIR}/prime_rl_opd_8node_full_vocab_dpsk_ctx81920_nodes345.sh"
