#!/usr/bin/env bash

# Shared CUDA build configuration. Source this file after setting CUDA_VERSION.
CUDA_VERSION="${CUDA_VERSION:-13.0.2}"

if [[ ! "${CUDA_VERSION}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
    echo "CUDA_VERSION must use MAJOR.MINOR.PATCH format, got: ${CUDA_VERSION}" >&2
    return 2 2>/dev/null || exit 2
fi

CUDA_MAJOR="${BASH_REMATCH[1]}"
CUDA_MINOR="${BASH_REMATCH[2]}"
CUDA_PATCH="${BASH_REMATCH[3]}"
CUDA_MAJOR_MINOR="${CUDA_MAJOR}.${CUDA_MINOR}"
CUDA_APT_SUFFIX="${CUDA_MAJOR}-${CUDA_MINOR}"
CUDA_PACKAGE_FAMILY="cu${CUDA_MAJOR}"
CUDA_WHEEL_TAG="cu${CUDA_MAJOR}${CUDA_MINOR}"
CUDA_ROOT="/usr/local/cuda-${CUDA_MAJOR_MINOR}"

case "${CUDA_MAJOR_MINOR}" in
    12.8)
        CUDA_BASE_IMAGE_VERSION="12.8"
        CUDA_KERNEL_WHEEL_TAG="cu128"
        CUDA_NCCL_APT_VERSION="12.9"
        CUDA_CUBLASMP_VERSION="0.5.1.65"
        # torch 2.11 cu128 requires cuda-bindings>=12.9.4,<13.
        CUDA_PYTHON_VERSION="12.9.7"
        ;;
    12.9)
        # PyTorch 2.11 has no CUDA 12.9 devel image or matching FA2/FA3 wheels.
        # Start from its CUDA 12.8 image and use the compatible cu128 kernels.
        CUDA_BASE_IMAGE_VERSION="12.8"
        CUDA_KERNEL_WHEEL_TAG="cu128"
        CUDA_NCCL_APT_VERSION="12.9"
        CUDA_CUBLASMP_VERSION="0.8.0.2023"
        CUDA_PYTHON_VERSION="12.9.7"
        ;;
    13.0)
        CUDA_BASE_IMAGE_VERSION="13.0"
        CUDA_KERNEL_WHEEL_TAG="cu130"
        CUDA_NCCL_APT_VERSION="13.1"
        CUDA_CUBLASMP_VERSION="0.8.0.2023"
        CUDA_PYTHON_VERSION="${CUDA_VERSION}"
        ;;
    *)
        echo "Unsupported CUDA_VERSION=${CUDA_VERSION}; supported versions: 12.8.x, 12.9.x, 13.0.x" >&2
        return 2 2>/dev/null || exit 2
        ;;
esac

CUDA_TOOLKIT_APT_SPEC="cuda-toolkit-${CUDA_APT_SUFFIX}=${CUDA_VERSION}-1"
CUDA_CUBLASMP_APT_SPEC="cublasmp-cuda-${CUDA_MAJOR}=${CUDA_CUBLASMP_VERSION}-1"
CUDA_NCCL_APT_SPEC="2.29.3-1+cuda${CUDA_NCCL_APT_VERSION}"
CUDA_HOME="${CUDA_HOME_OVERRIDE:-${CUDA_ROOT}}"
CUDA_PATH="${CUDA_PATH_OVERRIDE:-${CUDA_ROOT}}"
CUDAToolkit_ROOT="${CUDA_TOOLKIT_ROOT_OVERRIDE:-${CUDA_ROOT}}"
CUDACXX="${CUDACXX_OVERRIDE:-${CUDA_ROOT}/bin/nvcc}"

PYTORCH_INDEX_URL="${PYTORCH_INDEX_URL:-https://download.pytorch.org/whl/${CUDA_WHEEL_TAG}}"
TORCHAO_INDEX_URL="${TORCHAO_INDEX_URL:-https://download.pytorch.org/whl/nightly/${CUDA_WHEEL_TAG}}"
FLASHINFER_INDEX_URL="${FLASHINFER_INDEX_URL:-https://flashinfer.ai/whl/${CUDA_WHEEL_TAG}}"
FLASH_ATTN_WHEEL_NAME="flash_attn-2.8.3+${CUDA_KERNEL_WHEEL_TAG}torch2.11-cp312-cp312-linux_x86_64.whl"
FLASH_ATTN_WHEEL_URL="${FLASH_ATTN_WHEEL_URL:-https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.9.4/flash_attn-2.8.3%2B${CUDA_KERNEL_WHEEL_TAG}torch2.11-cp312-cp312-linux_x86_64.whl}"
FLASH_ATTN_3_WHEEL_NAME="flash_attn_3-3.0.0+20260511.${CUDA_KERNEL_WHEEL_TAG}torch2110cxx11abitrue.ab6632-cp39-abi3-linux_x86_64.whl"
FLASH_ATTN_3_WHEEL_URL="${FLASH_ATTN_3_WHEEL_URL:-https://github.com/windreamer/flash-attention3-wheels/releases/download/2026.05.11-5e0e3b1/flash_attn_3-3.0.0%2B20260511.${CUDA_KERNEL_WHEEL_TAG}torch2110cxx11abitrue.ab6632-cp39-abi3-linux_x86_64.whl}"
PREBUILT_WHEELS_DIR="${PREBUILT_WHEELS_DIR:-torch2.11+${CUDA_KERNEL_WHEEL_TAG}}"
VLLM_PREBUILT_WHEELS_DIR="${VLLM_PREBUILT_WHEELS_DIR:-torch2.11+${CUDA_WHEEL_TAG}}"

NVIDIA_NCCL_DIST="nvidia-nccl-${CUDA_PACKAGE_FAMILY}"
NVIDIA_CUBLASMP_DIST="nvidia-cublasmp-${CUDA_PACKAGE_FAMILY}"
NVSHMEM4PY_DIST="nvshmem4py-${CUDA_PACKAGE_FAMILY}"
if [ "${CUDA_MAJOR}" = "13" ]; then
    NVIDIA_CUDA_CCCL_DIST="nvidia-cuda-cccl"
    NVIDIA_CUDA_RUNTIME_DIST="nvidia-cuda-runtime"
    NVIDIA_CUTLASS_DSL_SPEC="${NVIDIA_CUTLASS_DSL_SPEC:-nvidia-cutlass-dsl[cu13]==4.5.2}"
else
    NVIDIA_CUDA_CCCL_DIST="nvidia-cuda-cccl-cu12"
    NVIDIA_CUDA_RUNTIME_DIST="nvidia-cuda-runtime-cu12"
    NVIDIA_CUTLASS_DSL_SPEC="${NVIDIA_CUTLASS_DSL_SPEC:-nvidia-cutlass-dsl==4.5.2}"
fi

export \
    CUDA_VERSION CUDA_MAJOR CUDA_MINOR CUDA_PATCH CUDA_MAJOR_MINOR CUDA_APT_SUFFIX \
    CUDA_PACKAGE_FAMILY CUDA_WHEEL_TAG CUDA_ROOT CUDA_BASE_IMAGE_VERSION \
    CUDA_KERNEL_WHEEL_TAG CUDA_NCCL_APT_VERSION CUDA_CUBLASMP_VERSION \
    CUDA_PYTHON_VERSION CUDA_TOOLKIT_APT_SPEC CUDA_CUBLASMP_APT_SPEC \
    CUDA_NCCL_APT_SPEC CUDA_HOME CUDA_PATH CUDAToolkit_ROOT CUDACXX \
    PYTORCH_INDEX_URL TORCHAO_INDEX_URL FLASHINFER_INDEX_URL \
    FLASH_ATTN_WHEEL_NAME FLASH_ATTN_WHEEL_URL FLASH_ATTN_3_WHEEL_NAME \
    FLASH_ATTN_3_WHEEL_URL PREBUILT_WHEELS_DIR VLLM_PREBUILT_WHEELS_DIR NVIDIA_NCCL_DIST \
    NVIDIA_CUBLASMP_DIST NVIDIA_CUDA_CCCL_DIST NVIDIA_CUDA_RUNTIME_DIST \
    NVSHMEM4PY_DIST NVIDIA_CUTLASS_DSL_SPEC
